import { Router } from 'express';
import { healthRoutes } from './health.routes.js';
import { capabilitiesRoutes } from './capabilities.routes.js';
import { dashboardRoutes } from './dashboard.routes.js';
import { wlanRoutes } from './wlan.routes.js';
import { devicesRoutes } from './devices.routes.js';
import { groupsRoutes } from './groups.routes.js';
import { policiesRoutes } from './policies.routes.js';
import { portForwardingRoutes } from './portForwarding.routes.js';
import { ddnsRoutes } from './ddns.routes.js';
import { firewallRoutes } from './firewall.routes.js';
import { qosRoutes } from './qos.routes.js';
import { voipRoutes } from './voip.routes.js';
import { usbRoutes } from './usb.routes.js';
import { systemRoutes } from './system.routes.js';
import { speedTestRoutes } from './speedtest.routes.js';
import { diagnosticsRoutes } from './diagnostics.routes.js';
import { notificationsRoutes } from './notifications.routes.js';
import { authRoutes } from './auth.routes.js';
import { requireAppAuth } from '../services/appAuth.js';

export const apiRouter = Router();

apiRouter.use(healthRoutes);
apiRouter.use(authRoutes);
apiRouter.use(requireAppAuth);
apiRouter.use(capabilitiesRoutes);
apiRouter.use(dashboardRoutes);
apiRouter.use(wlanRoutes);
apiRouter.use(devicesRoutes);
apiRouter.use(groupsRoutes);
apiRouter.use(policiesRoutes);
apiRouter.use(portForwardingRoutes);
apiRouter.use(ddnsRoutes);
apiRouter.use(firewallRoutes);
apiRouter.use(qosRoutes);
apiRouter.use(voipRoutes);
apiRouter.use(usbRoutes);
apiRouter.use(systemRoutes);
apiRouter.use(speedTestRoutes);
apiRouter.use(diagnosticsRoutes);
apiRouter.use(notificationsRoutes);
