import type { CreateGroupRequest, CreatePolicyRequest, FeatureCapability, NotificationPreferences, RouterCompatibility, UpdateGroupRequest, UpdatePolicyRequest, UpdateDeviceRequest, WifiUpdateRequest } from '@router-manager/shared';
import { OID_LABELS, PROBED_OIDS, UNAVAILABLE_REASON, classifyRouterSupport, compatibilityMessage, writeReasonFor, writeStatusFor } from '@router-manager/shared';
import { nativeRouter, nativeAppPrefs } from './router-native';
import { readLocal, updateLocal } from './local-data';

const objects = (value: any): any[] => Array.isArray(value?.Object) ? value.Object : [];
const now = () => new Date().toISOString();
let requestQueue: Promise<unknown> = Promise.resolve();
let compatibility: RouterCompatibility | null = null;
let capabilityCache: Record<string, FeatureCapability> | null = null;
const delay = (ms:number) => new Promise((resolve)=>setTimeout(resolve,ms));
async function queued<T>(operation:()=>Promise<T>):Promise<T>{let value!:T;requestQueue=requestQueue.then(async()=>{value=await operation();await delay(100);});await requestQueue;return value;}
async function get(oid: string): Promise<any> { return queued(async()=>(await nativeRouter.daoGet<any>({ oid })).data); }
async function set(oid: string, payload: unknown, method: 'POST'|'PUT'='PUT'): Promise<any> { assertVerifiedWrite(oid); return queued(async()=>(await nativeRouter.daoSet<any>({ oid, payload, method })).data); }

async function detectCompatibility():Promise<RouterCompatibility>{if(compatibility)return compatibility;const status=await get('status');const info=objects(status)[0]?.DeviceInfo??{};const level=classifyRouterSupport(info.ModelName??'');compatibility={manufacturer:info.Manufacturer??'Unknown',model:info.ModelName??'Unknown router',firmware:info.SoftwareVersion??'Unknown',supportLevel:level,detectedAt:now(),message:compatibilityMessage(level)};return compatibility;}
function assertVerifiedWrite(oid:string){const feature=capabilityCache?.[oid];if(!feature||feature.write!=='verified')throw new Error(`${OID_LABELS[oid]??'This setting'} is read-only until its write protocol is verified for this firmware.`);}

export const directApi = {
  health: async () => ({ ok: true }),
  auth: { login: async () => ({ token: 'native', expiresAt: '9999-12-31T00:00:00.000Z', user: { username: 'router' } }), logout: () => nativeRouter.logout().then(() => ({ ok: true as const })) },
  capabilities: async () => { const router=await detectCompatibility();const capabilities:Record<string,FeatureCapability>={};for(const oid of PROBED_OIDS){try{await get(oid);const write=writeStatusFor(oid,router.supportLevel);capabilities[oid]={key:oid,label:OID_LABELS[oid],read:'available',write,reason:writeReasonFor(write),source:'live-probe',lastVerifiedFirmware:write==='verified'?router.firmware:null};}catch{capabilities[oid]={key:oid,label:OID_LABELS[oid],read:'unavailable',write:'blocked',reason:UNAVAILABLE_REASON,source:'live-probe',lastVerifiedFirmware:null};}}capabilityCache=capabilities;return{capabilities,compatibility:router}; },
  dashboard: async () => { const [status,wan] = await Promise.all([get('status'),get('wan')]); const d=objects(status)[0]?.DeviceInfo ?? {}; const w=objects(wan)[0] ?? {}; return { system:{manufacturer:d.Manufacturer??'',modelName:d.ModelName??'',description:d.Description??'',serialNumber:d.SerialNumber??'',softwareVersion:d.SoftwareVersion??'',hardwareVersion:d.HardwareVersion??'',upTimeSeconds:d.UpTime??0},wan:{connected:Boolean(w.IPAddress),type:w.Type??'',ipAddress:w.IPAddress??''} }; },
  wifi: { get: async () => ({ bands: objects(await get('wlan')).map((e:any)=>({index:e.Index,ssid:e.SSID,band:e.band,enabled:e.wlEnable,hidden:e.wlHide,mainSsid:e.MainSSID,channel:e.channel,bandwidth:e.bandwidth,securityMode:e.SecurityMode,pskDisplay:e.PskDisplay})) }), update: async (u:WifiUpdateRequest) => { const p:any={Index:u.index}; if(u.ssid!==undefined)p.SSID=u.ssid;if(u.psk!==undefined)p.PskDisplay=u.psk;if(u.enabled!==undefined)p.wlEnable=u.enabled;if(u.hidden!==undefined)p.wlHide=u.hidden;await set('wlan',p);return{ok:true as const}; } },
  devices: { list: async () => { const raw=await get('lanhosts'); const hosts=objects(raw)[0]?.lanhosts??[]; const stamp=now(); const activeMacs=new Set<string>(hosts.filter((h:any)=>h.Active).map((h:any)=>h.PhysAddress)); const devices=await updateLocal((local)=>{const result=hosts.map((h:any)=>{let seen=local.seen[h.PhysAddress];if(!seen){seen={firstSeenAt:stamp,lastSeenAt:stamp,name:h.HostName||'(unknown)',active:Boolean(h.Active)};local.seen[h.PhysAddress]=seen;local.events.unshift({id:local.nextId++,macAddress:h.PhysAddress,displayName:h.HostName||'(unknown)',eventType:'new_device',occurredAt:stamp});}else if(Boolean(seen.active)!==Boolean(h.Active)){local.events.unshift({id:local.nextId++,macAddress:h.PhysAddress,displayName:h.HostName||seen.name,eventType:h.Active?'device_online':'device_offline',occurredAt:stamp});}seen.lastSeenAt=stamp;seen.active=Boolean(h.Active);const x=local.overlays[h.PhysAddress];return{macAddress:h.PhysAddress,hostName:h.HostName||'(unknown)',customName:x?.customName??null,displayName:x?.customName||h.HostName||'(unknown)',ipAddress:h.IPAddress,active:h.Active,interfaceType:h.InterfaceType,connectionType:h.X_ZYXEL_ConnectionType,signalStrength:h.X_ZYXEL_SignalStrength??null,icon:x?.icon??null,notes:x?.notes??null,groupId:x?.groupId??null,isNew:Date.now()-Date.parse(seen.firstSeenAt)<86400000,firstSeenAt:seen.firstSeenAt,lastSeenAt:seen.lastSeenAt};});for(const [mac,seen] of Object.entries(local.seen)){if(seen.active&&!activeMacs.has(mac)){seen.active=false;local.events.unshift({id:local.nextId++,macAddress:mac,displayName:seen.name,eventType:'device_offline',occurredAt:stamp});}}for(const group of local.groups)group.deviceCount=Object.values(local.overlays).filter((item)=>item.groupId===group.id).length;return result;});return{devices}; }, update: async(mac:string,u:UpdateDeviceRequest)=>{await updateLocal(d=>{d.overlays[mac]={macAddress:mac,customName:u.customName!==undefined?u.customName:d.overlays[mac]?.customName??null,icon:u.icon!==undefined?u.icon:d.overlays[mac]?.icon??null,notes:u.notes!==undefined?u.notes:d.overlays[mac]?.notes??null,groupId:u.groupId!==undefined?u.groupId:d.overlays[mac]?.groupId??null};d.events.unshift({id:d.nextId++,macAddress:mac,displayName:u.customName||d.seen[mac]?.name||mac,eventType:'settings_changed',occurredAt:now(),detail:'Device details updated'});});return{ok:true as const};}, events:async()=>({events:(await readLocal()).events.slice(0,100)}) },
  groups:{list:async()=>({groups:(await readLocal()).groups}),create:async(i:CreateGroupRequest)=>({group:await updateLocal(d=>{const t=now();const g={id:d.nextId++,name:i.name,icon:i.icon??null,deviceCount:0,createdAt:t,updatedAt:t};d.groups.push(g);return g;})}),update:async(id:number,i:UpdateGroupRequest)=>({group:await updateLocal(d=>{const g=d.groups.find(x=>x.id===id);if(!g)throw new Error('Group not found');if(i.name!==undefined)g.name=i.name;if(i.icon!==undefined)g.icon=i.icon;g.updatedAt=now();return g;})}),remove:async(id:number)=>{await updateLocal(d=>{d.groups=d.groups.filter(g=>g.id!==id);Object.values(d.overlays).forEach(x=>{if(x.groupId===id)x.groupId=null;});});return{ok:true as const};}},
  policies:{list:async()=>({policies:(await readLocal()).policies}),raw:async()=>({wlanSchAccess:await get('wlan_sch_access').catch(String),scheduler:await get('scheduler').catch(String),parentalControl:await get('paren_ctl').catch(String)}),create:async(i:CreatePolicyRequest)=>({policy:await updateLocal(d=>{const t=now();const p:any={...i,id:d.nextId++,enabled:i.enabled??true,enforcement:'unenforced',createdAt:t,updatedAt:t};d.policies.push(p);return p;})}),update:async(id:number,i:UpdatePolicyRequest)=>({policy:await updateLocal(d=>{const p:any=d.policies.find(x=>x.id===id);if(!p)throw new Error('Policy not found');Object.assign(p,i,{updatedAt:now()});return p;})}),remove:async(id:number)=>{await updateLocal(d=>{d.policies=d.policies.filter(p=>p.id!==id);});return{ok:true as const};}},
  diagnostics:{run:async()=>{const started=performance.now();let status:any=null;let wan:any=null;try{status=await get('status');wan=await get('wan');}catch{const result={checkedAt:now(),routerLatencyMs:null,wanConnected:false,checks:[{key:'router' as const,label:'Router',status:'fail' as const,detail:'The router did not respond.'},{key:'wan' as const,label:'Internet',status:'fail' as const,detail:'WAN status could not be read.'},{key:'dns' as const,label:'DNS',status:'warning' as const,detail:'DNS could not be checked.'}]};await updateLocal(d=>{d.diagnostics.unshift(result);});return{result};}const latency=Math.round(performance.now()-started);const w=objects(wan)[0]??{};const connected=Boolean(w.IPAddress);const dns=Array.isArray(w.DNSServer)?w.DNSServer.join(', '):String(w.DNSServer??'Not reported');const result={checkedAt:now(),routerLatencyMs:latency,wanConnected:connected,checks:[{key:'router' as const,label:'Router',status:'pass' as const,detail:`Responded in ${latency} ms`},{key:'wan' as const,label:'Internet',status:connected?'pass' as const:'fail' as const,detail:connected?`WAN address ${w.IPAddress}`:'No WAN address reported'},{key:'dns' as const,label:'DNS',status:w.DNSServer?'pass' as const:'warning' as const,detail:dns}]};void status;await updateLocal(d=>{d.diagnostics.unshift(result);d.events.unshift({id:d.nextId++,macAddress:null,displayName:'Network check',eventType:'diagnostic_result',occurredAt:result.checkedAt,detail:connected?'All essential checks passed':'Internet connection needs attention'});});return{result};}},
  speedTest:{run:async()=>{throw new Error('Phone speed testing is planned but is not enabled in this local-only release.');}},
  notifications:{get:async()=>({preferences:(await readLocal()).notifications}),update:async(u:Partial<NotificationPreferences>)=>{const preferences=await updateLocal(d=>{d.notifications={...d.notifications,...u};return d.notifications;});await nativeAppPrefs.setNotificationPrefs(preferences).catch(()=>{});return{preferences};}},
  portForwarding:{list:async()=>({rules:objects(await get('nat')).map((r:any,i:number)=>({index:r.Index??i,enable:Boolean(r.Enable),name:r.Name??`Rule ${i+1}`,protocol:r.Protocol??'',externalPort:r.ExternalPort??'',internalIp:r.InternalClient??'',internalPort:r.InternalPort??''}))}),add:async(r:any)=>{await set('nat',{Enable:r.enable,Name:r.name,Protocol:r.protocol,ExternalPort:r.externalPort,InternalClient:r.internalIp,InternalPort:r.internalPort},'POST');return{ok:true as const};},remove:async(index:number)=>{await set('nat',{Index:index});return{ok:true as const};}},
  ddns:{get:async()=>{const e=objects(await get('dns'))[0]??{};return{config:{enable:e.ddnsEnable??false,provider:e.ddnsProvider??'',hostname:e.ddnsHostname??'',username:e.ddnsUsername??''}};},update:async(u:any)=>{await set('dns',{ddnsEnable:u.enable,ddnsProvider:u.provider,ddnsHostname:u.hostname,ddnsUsername:u.username,ddnsPassword:u.password});return{ok:true as const};}},
  firewall:{get:async()=>({rules:objects(await get('firewall_acl')),cyberSecure:objects(await get('cyber_secure'))[0]??{}}),parentalControls:async()=>({parentalControls:objects(await get('paren_ctl'))[0]??{}})},
  qos:{get:async()=>{const e=objects(await get('qos'))[0];return{settings:{enable:e.Enable,upRate:e.UpRate,downRate:e.DownRate,minUpRate:e.MinUpRate,maxUpRate:e.MaxUpRate}};},update:async(u:any)=>{await set('qos',{Enable:u.enable,UpRate:u.upRate,DownRate:u.downRate});return{ok:true as const};}},
  voip:{list:async()=>({lines:objects(await get('sip_account')).map((e:any)=>({index:e.Index,directoryNumber:e.DirectoryNumber,enable:e.Enable,status:e.Status,authUserName:e.AuthUserName}))})},
  usb:{get:async()=>{const e=objects(await get('usb_info'))[0]??{};return{status:{connected:Array.isArray(e['Usb Info'])?e['Usb Info'].length>0:Boolean(e['Usb Info']),raw:e}};}},
  system:{get:async()=>{const[a,b]=await Promise.all([get('user_account'),get('tr69')]);return{account:objects(a)[0]??null,remoteManagement:objects(b)[0]??null};},reboot:async()=>{throw new Error('Router reboot is read-only until this firmware command is verified.');},changePassword:async()=>{throw new Error('Password changes are disabled until this firmware command is verified.');}}
};
